#!/usr/bin/env php
<?php

// +----------------------------------------------------------------------
// | ThinkPHP CLI 入口文件
// +----------------------------------------------------------------------

namespace think;

// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 加载环境变量
if (is_file(__DIR__ . '/.env')) {
    (new \think\Env())->load(__DIR__ . '/.env');
}

// 应用初始化
(new App())->console->run();
